os:
  -osx

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

language: cpp

compiler:
	- clang
  - gcc

before_install:
	- pip install --user cpp-coveralls

script:
	- cmake -H. -Bbuild -DBUILD_TESTS=ON -DCOVERAGE=ON
	- cmake --build build/
	- cmake --build build --target test -- ARGS=--verbose
